# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "eventmachine", "~>1.0.3"

gem "hoe-yard", ">=0.1.2", :group => [:development, :test]
gem "hoe", "~>3.7.1", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0.0", :group => [:development, :test]
gem "hoe-bundler", "~>1.2.0", :group => [:development, :test]
gem "simplecov", "~>0.7.1", :group => [:development, :test]
gem "simplecov-console", "~>0.1.1", :group => [:development, :test]
gem "minitest", "~>5.0.8", :group => [:development, :test]
gem "minitest-debugger", "~>1.0.2", :group => [:development, :test]
gem "minitest-reporters", "~>1.0.4", :group => [:development, :test]

# vim: syntax=ruby
